// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lynoasmjxnknoihsrdyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5bm9hc21qeG5rbm9paHNyZHlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MDMyNjksImV4cCI6MjA2Nzk3OTI2OX0.-jtYDNnIz_nSG4QEcDt69L5qVOoQrxbIiO6cjBFjv9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});